[workspace]
resolver = "3"
members = [
    "rustecal",
    "rustecal-core",
    "rustecal-pubsub",
    "rustecal-service",
    "rustecal-sys",
    "rustecal-types-bytes",
    "rustecal-types-protobuf",
    "rustecal-types-serde",
    "rustecal-types-string",
    "rustecal-samples/benchmarks/performance_receive",
    "rustecal-samples/benchmarks/performance_send",
    "rustecal-samples/monitoring/logging_receive",
    "rustecal-samples/monitoring/monitoring_receive",
    "rustecal-samples/pubsub/blob_send",
    "rustecal-samples/pubsub/blob_receive",
    "rustecal-samples/pubsub/hello_send",
    "rustecal-samples/pubsub/hello_receive",
    "rustecal-samples/pubsub/person_send",
    "rustecal-samples/pubsub/person_receive",
    "rustecal-samples/pubsub/serde_send",
    "rustecal-samples/pubsub/serde_receive",
    "rustecal-samples/service/math_client",
    "rustecal-samples/service/mirror_client",
    "rustecal-samples/service/mirror_client_instances",
    "rustecal-samples/service/mirror_server",
]
